# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1115b7554e45f1d88a55a0f2bcb2fa3325017337a960881976b38bb3c5c6b7e1e5273d2f62a023386a5e0acfd6518bdca9f6256db981e6c4c1ef3452c734d757

test:
  secret_key_base: f5697373b7e57b319aaecdc80254e8b3644a193fb0bda5b1581c2302b9f99e7c3be73025574a7b07a835109c9b2a80f6f27a8eeae8c3c3932b1c74e585040754

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
